apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-es-sync-config
data:
  config.yaml: |
    sync_config:
      tables:
        - name: "your_table_name"
          index_name: "your_es_index"
          timestamp_column: "updated_at"
          primary_key: "id"
      
      sync_interval: 10
      min_batch_size: 100
      max_batch_size: 5000
      rate_limit: 1000
      pool_size: 5
