apiVersion: v1
kind: Secret
metadata:
  name: pg-es-sync-secrets
type: Opaque
data:
  # Base64 encoded values - replace with your actual encoded values
  PG_HOST: cG9zdGdyZXM=  # postgres
  PG_PORT: NTQzMg==      # 5432
  PG_DATABASE: ZGI=      # db
  PG_USER: dXNlcg==     # user
  PG_PASSWORD: cGFzcw==  # pass
  ES_HOST: ZWxhc3RpY3NlYXJjaA==  # elasticsearch
  ES_PORT: OTIwMA==     # 9200
  ES_USER: ZWxhc3RpYw==  # elastic
  ES_PASSWORD: cGFzcw==  # pass
  ES_USE_SSL: ZmFsc2U=  # false
